### ISSUE TITLE
Too many requests`

### ISSUE THREAD

**Issue by connorv001** [AdirthaBorgohain/intelliweb-GPT#1]
Litearlly running it for the first tiem:

```
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: multi-qa-MiniLM-L6-cos-v1
INFO:sentence_transformers.SentenceTransformer:Use pytorch device: cpu
WARNING:llama_index.llm_predictor.base:Unknown max input size for gpt-3.5-turbo, using defaults.
Using Google Web Search and searching for 'Connor Verlekar'...!
Traceback (most recent call last):
  File "/home/shubham/1-lang/test", line 5, in <module>
    answer_dict = generate_answer(query)
  File "/home/shubham/1-lang/intelliweb_GPT/generate.py", line 31, in generate_answer
    urls = [r for r in res]
  File "/home/shubham/1-lang/intelliweb_GPT/generate.py", line 31, in <listcomp>
    urls = [r for r in res]
  File "/home/shubham/.local/lib/python3.10/site-packages/googlesearch/__init__.py", line 54, in search
    resp = _req(escaped_term, num_results - start,
  File "/home/shubham/.local/lib/python3.10/site-packages/googlesearch/__init__.py", line 23, in _req
    resp.raise_for_status()
  File "/home/shubham/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3DConnor%252BVerlekar%26num%3D7%26hl%3Den%26start%3D0&hl=en&q=EhAqAQT5wBJQkwAAAAAAAAABGNz_kqIGIjBo0FE-QdiYqUNQu8TfYti1EdjdCwiNsQADSMA5AVcPacRbyHu-Z1sW9UTZMNn0vM8yAXI
```

**Comment by AdirthaBorgohain** [comment]
Hi. You are getting this error because google seems to have blocked you IP address for some reason. Maybe you had tried fetching data from google earlier programmatically? In order to get this running, you'll need to use something like https://serpapi.com/ or https://serper.dev/ (cheaper) to fetch the results from google. I have been meaning to integrate these to the code as well so one can use whichever tool he/she likes.

**Comment by AdirthaBorgohain** [comment]
@connorv001 I have just pushed the code that uses https://serper.dev to initially fetch the relevant urls. You'll need to create an account on  https://serper.dev and generate an API Key. It gives you 1000 requests for free initially. Copy the API key to the `SERPER_API_KEY` env variable in .env file. Everything should work after that. Let me know.

Use the `generate_answer` method like this: `generate_answer(query, use_serper_api=True)` By default the `use_serper_api` argument is set to False.

**Comment by connorv001** [comment]
Still gives the same error @AdirthaBorgohain

**Comment by AdirthaBorgohain** [comment]
@connorv001 Can you pull from the repo now and run the `example_usage.py` file? Don't forget to add the `SERPER_API_KEY` key to `.env` file before running.

**Comment by connorv001** [comment]
Thank you it worked now.
