### ISSUE TITLE
ValueError: A single term is larger than the allowed chunk size

### ISSUE THREAD

**Issue by GavinZJZhang** [AdirthaBorgohain/intelliweb-GPT#3]
When i try the query="twitter's CEO?"

I got this error:
ValueError: A single term is larger than the allowed chunk size.
Term size: 394
Chunk size: 352Effective chunk size: 352

**Comment by AdirthaBorgohain** [comment]
Hi @GavinZJZhang ! Can you try now? I bumped up the llama-index version and made the necessary changes to the index querying code.
