### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by envieme** [AdirthaBorgohain/intelliweb-GPT#4]
ERROR: Cannot install -r requirements.txt (line 8) and trafilatura==1.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    requests 2.28.1 depends on charset-normalizer<3 and >=2
    trafilatura 1.5.0 depends on charset-normalizer>=3.1.0; python_version >= "3.7"

**Comment by AdirthaBorgohain** [comment]
Hello. I just refactored the whole codebase and made a lot of changes. Can you try installing the packages now?

**Comment by envieme** [comment]
Yes it works very well now. Thank you!
